name: Build and publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  publish:
    needs: build
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete old package versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'xyz.malkki.microservice-testing-tool'
          min-versions-to-keep: 3